### ISSUE TITLE
SBI DBCN Console in Salus

### ISSUE THREAD

**Issue by atishp04** [rivosinc/salus#123]
Can we implement SBI debug console extension in Salus ?
https://lists.riscv.org/g/tech-unixplatformspec/message/1815
The Linux patches can be found in the above email. Anup reports that it improves guest booting time by ~30%.
It should help boot time of Linux in Salus as well

**Comment by abrestic-rivos** [comment]
So DBCN works okay for Salus as its implemented today since Salus owns the physical console, but things get more complicated when the TSM doesn't have exclusive ownership of the console (for example, in the host-in-HS deployment model). 

It seems like the `sbi_debug_console_puts()` calls from a TVM really should get forwarded to the host instead, and then the host can choose how to output the bytes (to a physical console, a file, etc). But then the question is how the host should access the buffer. Do we:
 - Require that the buffer be in shared memory? This would require the guest to set up shared memory pretty early in its boot sequence, and may look a little odd from an API perspective given that other SBI calls that take pointers (e.g. the attestation API) don't require the memory to be shared.
 - Use a bounce buffer? Adds a bunch of complexity to the host and/or TSM. Probably needs another TEEH API just to handle this particular case.

I'd be inclined to go with the former.

**Comment by abrestic-rivos** [comment]
I'm not sure we need to invent another shared-memory communication mechanism for this single use-case :)

Given that DBCN is intended to be used during early boot, I feel like we should try to keep things as simple as possible and not deviate too much from the legacy (non-TVM) path.

**Comment by dgreid** [comment]
Let's require the buffers to be in shared memory. That makes the sharing more explicit from the guest's standpoint and will reduce accidental data leaks.

**Comment by dgreid** [comment]
I've got the code started to get the host prints working at least, will post it this week.

**Comment by atishp04** [comment]
Shared memory approach sounds good to me as well.
