### ISSUE TITLE
Make CSR shared memory interface be per-physical-CPU

### ISSUE THREAD

**Issue by atishp04** [rivosinc/salus#124]
Currently, TvmCpuNumRegisterSets/TvmCpuGetRegisterSet interface is defined per VM. 
It is defined as per VM in case TSM need to provide different layouts to different VMs. This provides more flexibility for TVM owners to selectively disable/enable extensions->shared memory layout in the future.

However, every VM has to make at least 4~5 ECALLS to retrieve the shared memory layout. This may affect the boot time of each VM. We may not want to penalize every VM creation for a corner case. We can always define special VMID value (-1) or additional flags to indicate the host wants global layout for all TVMs.

There are pros and cons in both methods. This is just a place holder issue created to address this issue in the future.

**Comment by abrestic-rivos** [comment]
Per offline discussion, we've decided to make the CSR shared-memory area per host (physical) CPU rather than per-vCPU and use a format similar to the proposed NACL extension for nested virtualization. The main reasons for doing this are:
- Future proofing of the shared memory structure by allocating space for all possible H-CSRs. This in turn makes the structure quite large (12kB), making it impractical to allocate them per-vCPU.
- Less awkward handling of certain H-CSRs (e.g. `hie`, `hgeie`, etc.) that affect the state of the state of the host CPU, rather than guest vCPU.
- Better alignment with (and perhaps setting up for some convergence with) the NACL extension.

Let's repurpose this bug to focus on that work.
