### ISSUE TITLE
Add  virtualization support for time/htimedelta...

### ISSUE THREAD

**Issue by atulkharerivos** [rivosinc/salus#46]
We need to figure the right approach for virtualization of these CSRs.

**Comment by atulkharerivos** [comment]
Updating the context per offline chat with @atishp04. 

1. The current implementation allows VMs to access CSR_TIME directly, and an alternative approach is to trap on the CSR access and emulate it. 
2. The current implementation doesn't calculate the correct time delta when programming htimedelta. This needs to fixed if we decide to stick with the approach of allowing direct CSR access.

**Comment by abrestic-rivos** [comment]
Proposed plan:
- Latch a TVM's `htimedelta` to `-time` the first time the TVM is run so that the TVM's effective start `time` is 0.
- Salus reports `htimedelta` of the TVM in the shared-memory area so that the VMM can correctly interpret the TVM's `vstimecmp`. Writes to `htimedelta` in the shared memory area are ignored; Salus always restores the `htimedelta` value that was latched at the start of TVM execution.
- When we support migration, adjustment of the TVM's `htimedelta` will be part of the migration flow such that the TVM's `time` appears contiguous across migration.

Assumption: `time` is read-only and synchronized across all harts in the system.

cc: @rajnesh-kanwal @rsahita

**Comment by atishp04** [comment]
Closed the duplicate issue and updated the label. 
I don't think we need to do anything specifically for time as time is accessible in TVMs via hcounteren.

**Comment by rajnesh-kanwal** [comment]
Closing as htimedelta support has been merged. https://github.com/rivosinc/salus/pull/233
